import { z } from 'zod';

/**
 * The analytics contour.
 *
 * The split that matters, and the reason this module is small: **the database
 * is already the analytics store for everything that moved money.** Openings,
 * deposits, battles, referrals and withdrawals are rows with amounts and
 * timestamps, and a report over them is a query. Re-emitting them as events
 * would create a second set of numbers that can disagree with the ledger, and
 * when a report and the ledger disagree the report is the one nobody trusts
 * again.
 *
 * So the event stream carries only what the database cannot answer: who arrived,
 * where from, what they looked at, and where they stopped. Everything else is
 * computed from the tables that already exist, and the two meet in the funnel —
 * an event-based top, a ledger-based bottom.
 */

/** Events the browser is allowed to report. */
export const AnalyticsEventType = {
  PAGE_VIEW: 'page_view',
  /** The Steam button was pressed — the last step before we lose the visitor to the redirect. */
  SIGN_IN_STARTED: 'sign_in_started',
  /** The top-up dialog was opened, which is not the same as topping up. */
  DEPOSIT_OPENED: 'deposit_opened',
  /** A promo code was typed into it. */
  PROMO_TRIED: 'promo_tried',
  /** A battle was created or joined from the lobby — the click, not the settled battle. */
  BATTLE_INTENT: 'battle_intent',
  /** An invite link was followed. */
  REFERRAL_VISIT: 'referral_visit',
} as const;
export type AnalyticsEventType = (typeof AnalyticsEventType)[keyof typeof AnalyticsEventType];

export const ANALYTICS_EVENT_TYPES = Object.values(AnalyticsEventType);

/** How many events one request may carry. The client batches on a short timer. */
export const ANALYTICS_BATCH_MAX = 20;

/**
 * One reported event.
 *
 * `anonId` is not in the payload: the client sends it once per batch, because a
 * batch comes from one browser by definition and repeating it per event is only
 * a way for the two to disagree.
 */
export const analyticsEventSchema = z.object({
  type: z.enum(ANALYTICS_EVENT_TYPES as [string, ...string[]]),
  /** Same-origin path only; a full URL would let a caller write anything into reports. */
  path: z.string().trim().max(512).optional(),
  referrer: z.string().trim().max(512).optional(),
  utmSource: z.string().trim().max(120).optional(),
  utmMedium: z.string().trim().max(120).optional(),
  utmCampaign: z.string().trim().max(120).optional(),
  /** A small bag of extra detail. Capped so a report cannot be filled with prose. */
  meta: z.record(z.string(), z.union([z.string().max(200), z.number(), z.boolean()])).optional(),
});
export type AnalyticsEventInput = z.infer<typeof analyticsEventSchema>;

export const analyticsCollectSchema = z.object({
  /**
   * Stable per browser, generated by the client. It is not an identity: it
   * exists so "visitors" is not the same number as "page views", and it is
   * replaced whenever the browser forgets it.
   */
  anonId: z.string().trim().min(8).max(64),
  /** Resets after a gap of inactivity, so sessions are countable. */
  sessionId: z.string().trim().min(8).max(64),
  events: z.array(analyticsEventSchema).min(1).max(ANALYTICS_BATCH_MAX),
});
export type AnalyticsCollectInput = z.infer<typeof analyticsCollectSchema>;

/** How long a browser may be idle before its next event starts a new session. */
export const SESSION_IDLE_MS = 30 * 60 * 1000;

/**
 * The metrics rolled up per day.
 *
 * A dashboard over a month of raw rows is a dozen aggregates across millions of
 * openings, every time somebody opens the page. These are computed once a night
 * into one row per day per metric, which makes the history cheap to read and
 * keeps it after the raw events are pruned. The live day is still computed
 * directly — an operator watching a promotion cannot wait until tomorrow.
 */
export const MetricKey = {
  VISITORS: 'visitors',
  SESSIONS: 'sessions',
  PAGE_VIEWS: 'page_views',
  SIGNUPS: 'signups',
  ACTIVE_PLAYERS: 'active_players',
  OPENINGS: 'openings',
  WAGERED: 'wagered',
  WON: 'won',
  GGR: 'ggr',
  DEPOSIT_COUNT: 'deposit_count',
  DEPOSIT_TOTAL: 'deposit_total',
  WITHDRAWAL_COUNT: 'withdrawal_count',
  WITHDRAWAL_TOTAL: 'withdrawal_total',
  SELL_TOTAL: 'sell_total',
  BATTLES: 'battles',
  BATTLE_ENTRIES: 'battle_entries',
  BONUS_SPINS: 'bonus_spins',
  PROMO_BONUS: 'promo_bonus',
  REFERRAL_ACCRUED: 'referral_accrued',
} as const;
export type MetricKey = (typeof MetricKey)[keyof typeof MetricKey];

export const METRIC_KEYS = Object.values(MetricKey);

/** Which metrics are money, so a chart knows whether to format them as such. */
export const MONEY_METRICS = new Set<MetricKey>([
  MetricKey.WAGERED,
  MetricKey.WON,
  MetricKey.GGR,
  MetricKey.DEPOSIT_TOTAL,
  MetricKey.WITHDRAWAL_TOTAL,
  MetricKey.SELL_TOTAL,
  MetricKey.PROMO_BONUS,
  MetricKey.REFERRAL_ACCRUED,
]);

export interface TimeSeriesPoint {
  /** `YYYY-MM-DD`, in UTC — the same day boundary the rollup uses. */
  date: string;
  value: number;
}

/** A day key, UTC. Reports must not move when the operator travels. */
export function dayKey(date: Date): string {
  return date.toISOString().slice(0, 10);
}

export function addDays(date: Date, days: number): Date {
  const next = new Date(date);
  next.setUTCDate(next.getUTCDate() + days);
  return next;
}

/**
 * Every day between two dates, inclusive.
 *
 * A series with missing days is drawn as a straight line across them, which is
 * a lie: no data is not the same as no change. The gaps are filled with zeros
 * here so every chart in the panel agrees about that.
 */
export function fillSeries(
  rows: readonly TimeSeriesPoint[],
  from: Date,
  to: Date,
): TimeSeriesPoint[] {
  const byDate = new Map(rows.map((row) => [row.date, row.value]));
  const series: TimeSeriesPoint[] = [];
  for (let cursor = new Date(dayKey(from)); cursor <= to; cursor = addDays(cursor, 1)) {
    const key = dayKey(cursor);
    series.push({ date: key, value: byDate.get(key) ?? 0 });
  }
  return series;
}

/** A share, with the division by zero that reports are full of handled once. */
export function share(part: number, whole: number): number {
  return whole > 0 ? part / whole : 0;
}

export interface FunnelStepInput {
  key: string;
  count: number;
}

export interface FunnelStep extends FunnelStepInput {
  /** Share of the first step. */
  ofFirst: number;
  /** Share of the step before it — where the drop-off actually is. */
  ofPrevious: number;
}

/**
 * The funnel, with both conversions.
 *
 * Two numbers rather than one because they answer different questions: share
 * of the top says how much of the traffic ends up playing, share of the
 * previous step says which step is losing them. A funnel with only the first is
 * a funnel where every step after a bad one looks bad.
 */
export function funnel(steps: readonly FunnelStepInput[]): FunnelStep[] {
  const first = steps[0]?.count ?? 0;
  return steps.map((step, index) => ({
    ...step,
    // The first step is the reference, so it is all of itself by definition —
    // including on a day with no traffic at all, where a share computed from
    // the count would render the top of the funnel as 0% and read as a bug.
    ofFirst: index === 0 ? 1 : share(step.count, first),
    ofPrevious: index === 0 ? 1 : share(step.count, steps[index - 1]!.count),
  }));
}

export interface RetentionRow {
  /** The week the players signed up in, as the Monday of that week. */
  cohort: string;
  size: number;
  /** Share of the cohort still playing in week 0, 1, 2 … */
  weeks: number[];
}

/** The Monday of a date's week, UTC. */
export function weekKey(date: Date): string {
  const monday = new Date(dayKey(date));
  // getUTCDay: 0 is Sunday, which is the end of the week here, not the start.
  const offset = (monday.getUTCDay() + 6) % 7;
  return dayKey(addDays(monday, -offset));
}

/**
 * Turns sign-up and activity dates into a cohort grid.
 *
 * Pure so the shape of the table is testable: an off-by-one in a retention
 * matrix is invisible on screen and changes every conclusion drawn from it.
 */
export function retention(
  players: ReadonlyArray<{ signedUpAt: Date; activeAt: readonly Date[] }>,
  weeksWide: number,
): RetentionRow[] {
  const cohorts = new Map<string, { size: number; weeks: number[] }>();

  for (const player of players) {
    const cohort = weekKey(player.signedUpAt);
    const row = cohorts.get(cohort) ?? { size: 0, weeks: new Array(weeksWide).fill(0) };
    row.size += 1;

    // A player counts once per week however often they played in it.
    const seen = new Set<number>();
    for (const active of player.activeAt) {
      const offset = Math.floor(
        (new Date(weekKey(active)).getTime() - new Date(cohort).getTime()) / (7 * 86_400_000),
      );
      if (offset >= 0 && offset < weeksWide) seen.add(offset);
    }
    for (const offset of seen) row.weeks[offset] += 1;

    cohorts.set(cohort, row);
  }

  return [...cohorts.entries()]
    .sort((a, b) => (a[0] < b[0] ? 1 : -1))
    .map(([cohort, row]) => ({
      cohort,
      size: row.size,
      weeks: row.weeks.map((count) => share(count, row.size)),
    }));
}

/**
 * An axis maximum a human would have chosen.
 *
 * A chart whose axis tops out at 731 is a chart nobody can read a value off.
 * Rounded up to 1, 2 or 5 times a power of ten.
 */
export function niceMax(values: readonly number[]): number {
  const peak = Math.max(0, ...values);
  if (peak === 0) return 1;
  const magnitude = 10 ** Math.floor(Math.log10(peak));
  for (const step of [1, 2, 2.5, 5, 10]) {
    if (peak <= step * magnitude) return step * magnitude;
  }
  return 10 * magnitude;
}

/**
 * The polyline for a series, in SVG user units.
 *
 * The geometry is here rather than in the chart component because it is
 * arithmetic, and arithmetic in a component is arithmetic nobody tests. The
 * component keeps the axes, the labels and the colours.
 */
export function seriesPath(
  values: readonly number[],
  width: number,
  height: number,
  max = niceMax(values),
): string {
  if (values.length === 0) return '';
  if (values.length === 1) {
    const y = height - (values[0]! / max) * height;
    return `M 0 ${round(y)} L ${width} ${round(y)}`;
  }
  const step = width / (values.length - 1);
  return values
    .map((value, index) => {
      const x = round(index * step);
      const y = round(height - (value / max) * height);
      return `${index === 0 ? 'M' : 'L'} ${x} ${y}`;
    })
    .join(' ');
}

function round(value: number): number {
  return Math.round(value * 100) / 100;
}

// --- what the admin endpoints return ---------------------------------------

export interface AnalyticsKpis {
  visitors: number;
  sessions: number;
  pageViews: number;
  signups: number;
  activePlayers: number;
  openings: number;
  wagered: number;
  won: number;
  ggr: number;
  actualRtp: number;
  deposits: { count: number; total: number };
  withdrawals: { count: number; total: number };
  battles: number;
  bonusSpins: number;
  promoBonus: number;
  referralAccrued: number;
  /** Average revenue per active player, in minor units. */
  arppu: number;
}

export interface AnalyticsOverview {
  period: { from: string; to: string };
  kpis: AnalyticsKpis;
  /** The same KPIs over the period immediately before, for a comparison. */
  previous: AnalyticsKpis;
  series: Record<string, TimeSeriesPoint[]>;
  funnel: FunnelStep[];
}

export interface TrafficRow {
  source: string;
  medium: string;
  campaign: string;
  visitors: number;
  signups: number;
  /** Signups per visitor from this source. */
  conversion: number;
}

export interface PlayerRow {
  userId: string;
  username: string;
  avatarUrl: string | null;
  openings: number;
  wagered: number;
  won: number;
  /** What the site has made from them: wagered minus won, plus the fees. */
  ggr: number;
  deposits: number;
  withdrawals: number;
  lastSeenAt: string | null;
}

export interface FeatureRow {
  feature: string;
  users: number;
  events: number;
  wagered: number;
  ggr: number;
}

export interface AnalyticsEventRow {
  id: string;
  type: string;
  path: string | null;
  referrer: string | null;
  source: string | null;
  username: string | null;
  anonId: string;
  createdAt: string;
}
